server:
  port: 8898
eureka:
  instance:
    hostname: 127.0.0.1:8898
  client:
    service-url:
      defaultZone: http://127.0.0.1:8899/eureka,http://127.0.0.1:8897/eureka
    fetch-registry: false #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为false
    register-with-eureka: false #由于该应用为注册中心，所以设置为false, 代表不向注册中心注册自己
spring:
  application:
    name: eureka-server98