spring:
  application:
    name: eureka-server
server:
  port: 1111
eureka:
  instance:
    hostname: peer1 #需要修改本机host  映射 127.0.0.1 peer1
  client:
    service-url:
      defaultZone: http://peer2:2222/eureka,http://peer3:3333/eureka