server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/mulholland0318/mdcproject
          search-paths: /**
          username: mulholland0318
          password: github1986
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8899/eureka/,http://127.0.0.1:8898/eureka/,http://127.0.0.1:8897/eureka/
