server:
  port: 8811
spring:
  application:
    name: service-test
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8899/eureka,http://127.0.0.1:8898/eureka,http://127.0.0.1:8897